apiVersion: v1
kind: Namespace
metadata:
  name: wishlistdb
---
apiVersion: resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
   name: rg-aks-wishlist-cosmosdb
   namespace: wishlistdb
spec:
   location: uksouth
   azureName: rg-aks-wishlist-cosmosdb
---
apiVersion: documentdb.azure.com/v1beta20210515
kind: DatabaseAccount
metadata:
  name: cosmos-prod-festivetech-uksouth
  namespace: wishlistdb
spec:
  location: uksouth  
  owner:
    name: rg-aks-wishlist-cosmosdb
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: uksouth
---
apiVersion: documentdb.azure.com/v1beta20210515
kind: SqlDatabase
metadata:
  name: wishlist
  namespace: wishlistdb
spec:
  location: uksouth
  owner:
    name: cosmos-prod-festivetech-uksouth
  options:
    throughput: 400
  resource:
    id: wishlist
---
apiVersion: documentdb.azure.com/v1beta20210515
kind: SqlDatabaseContainer
metadata:
  name: item
  namespace: wishlistdb
spec:
  location: uksouth
  owner:
    name: wishlist
  resource:
    id: item
    partitionKey:
      kind: Hash
      paths: ["/id"]